### ISSUE TITLE
Move configuration from code to config file/CLI

### ISSUE THREAD

**Issue by otaj** [Lightning-AI/LAI-research-template-App#41]

**Comment by zippeurfou** [comment]
@otaj @aniketmaurya is this still relevant?

**Comment by otaj** [comment]
haven't looked at the code of this for a while, no idea.

**Comment by otaj** [comment]
but it seems to be

**Comment by aniketmaurya** [comment]
The configuration here means template class parameters. Users need to update the repo anyway so I think we don't need to create one more CLI. So we can close this.
